services:

    configsdb:
        restart: always
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
